"""generate_counterexamples node — generate JUnit tests targeting potential regressions."""

from pathlib import Path

from agent.state import Phase0State

_JUNIT_TEST_TEMPLATE = """// Auto-generated by SpecProof Phase 0
// Target: {target}
// Contract: {contract_id}

package com.specproof.demo;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.specproof.demo.dto.ChangeEmailRequest;
import com.specproof.demo.entity.User;
import com.specproof.demo.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
public class SpecProofGeneratedTest {{

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private ObjectMapper objectMapper;

    @BeforeEach
    void setUp() {{
        userRepository.deleteAll();
        User user = new User("testuser", "test@example.com");
        user.setPasswordHash("$2a$10$dummy");
        userRepository.save(user);
    }}

    @Test
    void {test_method_name}() throws Exception {{
        User user = userRepository.findAll().get(0);
        ChangeEmailRequest req = new ChangeEmailRequest("newemail@example.com");

        {test_body}
    }}
}}
"""


def generate_counterexamples_node(state: Phase0State) -> dict:
    """Generate JUnit counterexample tests based on contracts and static findings.

    Phase 0 generates deterministic tests for known patterns.
    Phase 1+ will use LLM to generate targeted tests.
    """
    static_findings = state.get("static_findings", [])
    head_workspace = state.get("head_workspace", "")

    generated_tests: list[str] = []

    # If auth bypass detected, generate an unauthenticated access test
    has_auth_issue = any(
        f.get("type") in ("annotation_removed", "missing_auth_annotation")
        for f in static_findings
    )

    if has_auth_issue:
        auth_test = _JUNIT_TEST_TEMPLATE.format(
            target="@PreAuthorize removed — verify 401 for unauthenticated",
            contract_id="AUTH-01",
            test_method_name="changeEmailWithoutAuthMustReturn401InHead",
            test_body=(
                'mockMvc.perform(put("/api/users/{id}/email", user.getId())\n'
                '                .contentType(MediaType.APPLICATION_JSON)\n'
                '                .content(objectMapper.writeValueAsString(req)))\n'
                '                .andExpect(status().isUnauthorized());'
            ),
        )
        generated_tests.append(auth_test)

    # If no specific findings, generate a general regression test
    if not generated_tests:
        auth_test = _JUNIT_TEST_TEMPLATE.format(
            target="general regression",
            contract_id="GEN-01",
            test_method_name="changeEmailRegressionTest",
            test_body=(
                'mockMvc.perform(put("/api/users/{id}/email", user.getId())\n'
                '                .contentType(MediaType.APPLICATION_JSON)\n'
                '                .content(objectMapper.writeValueAsString(req)))\n'
                '                .andExpect(status().isOk());'
            ),
        )
        generated_tests.append(auth_test)

    # Write generated test to head workspace
    test_path = ""
    if head_workspace:
        test_dir = Path(head_workspace) / "src" / "test" / "java" / "com" / "specproof" / "demo"
        test_dir.mkdir(parents=True, exist_ok=True)
        test_file = test_dir / "SpecProofGeneratedTest.java"
        test_file.write_text(generated_tests[0], encoding="utf-8")
        test_path = str(test_file)

    return {
        "generated_tests_path": test_path,
    }
