"""Full capsule replay batch runner — real replay success rate (主计划 §5.9 / 阶段2).

Enumerates every capsule under capsules/ (zip payloads, extracted capsule
directories and the object-metadata store), replays each one through the
existing replay path (cli/specproof/commands/replay.py) inside a throwaway
git worktree, and classifies the outcome into exactly one of four buckets:

  same_conclusion        the capsule's recorded conclusion was reproduced
  env_mismatch           replay cannot run in this environment: no pwsh/bash
                         executor, no git, missing base/head refs, Maven
                         distribution/dependency download blocked, Docker
                         required — always with the exact reason, never faked
  evidence_inconsistent  the capsule's recorded evidence does not verify:
                         manifest.json missing/unreadable, manifest_digest
                         recompute mismatch, evidence_digest disagreement,
                         metadata-store payload digest mismatch
  replay_failed          replay ran but did not reproduce the conclusion:
                         run script failure, no verdict, or a verdict that
                         contradicts the recorded evidence

Verdict semantics. The capsule records its own claim in the blocker_check
blocker conditions. When 2_base_head_execution is true the capsule claims a
differential regression (base side green, head side red), so only a run script verdict of
"REGRESSION CONFIRMED" is the same conclusion. Capsules whose recorded
evidence is static-only carry no runtime claim; a runtime confirmation still
counts as the same conclusion (it strengthens it), but any other verdict
does not reproduce the finding and is reported as replay_failed.

The run scripts are executed unmodified, exactly as generated by
agent/nodes/create_capsule.py — observed replay defects are reported in the
reasons, never patched around.

Outputs (overwritten on every run):
  docs/eval/replay-results.json — machine-readable results
  docs/eval/replay-results.md   — human-readable summary with success rate

Usage:
  python scripts/bench_replay.py                 # full run, all capsules
  python scripts/bench_replay.py --limit 3       # smoke run, first 3 capsules
  python scripts/bench_replay.py --keep-worktree # keep the temp worktree
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import time
import zipfile
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from storage.object_metadata import (  # noqa: E402
    ObjectMetadata,
    ObjectMetadataStore,
    default_object_metadata_store,
    normalize_payload_digest,
    payload_sha256_of_file,
)

OUTCOME_SAME = "same_conclusion"
OUTCOME_ENV = "env_mismatch"
OUTCOME_EVIDENCE = "evidence_inconsistent"
OUTCOME_FAILED = "replay_failed"
OUTCOMES: tuple[str, ...] = (OUTCOME_SAME, OUTCOME_ENV, OUTCOME_EVIDENCE, OUTCOME_FAILED)

VERDICT_CONFIRMED = "REGRESSION CONFIRMED"
VERDICT_FIX = "UNEXPECTED FIX"
VERDICT_AMBIGUOUS = "AMBIGUOUS"
VERDICT_COMPLIANT = "COMPLIANT"
NO_RUNTIME_CLAIM = "NO_RUNTIME_CLAIM"

DEFAULT_TIMEOUT_S = 1800.0
CLI_TIMEOUT_S = 600.0
GATE_REPLAY_SUCCESS_RATE = 0.95

_VERDICT_RE = re.compile(
    r">>\s*(REGRESSION CONFIRMED|UNEXPECTED FIX|AMBIGUOUS|COMPLIANT)\s*<<"
)
_EXIT_CODE_RE = re.compile(r"(Base|Head) test exit code:\s*(\d+)")
_SHA256_HEX_RE = re.compile(r"^[0-9a-f]{64}$")

# (output pattern, human reason) pairs for environment failures. These win
# over a parsed verdict except when the verdict is REGRESSION CONFIRMED.
_ENV_FAILURE_PATTERNS: tuple[tuple[str, str], ...] = (
    (r"ERROR:\s*Java not found", "Java is not installed on PATH (run script requires JDK 21+)"),
    (r"Cannot checkout base ref", "base ref missing from the replay worktree"),
    (r"Cannot checkout head ref", "head ref missing from the replay worktree"),
    (r"is not a git repository", "replay target is not a git repository"),
    (r"Could not transfer artifact", "Maven dependency download failed (network unavailable)"),
    (r"Unable to connect to", "Maven repository connection failed (network unavailable)"),
    (r"Connection timed out", "Maven repository connection timed out (network unavailable)"),
    (r"Connection refused", "Maven repository connection refused (network unavailable)"),
    (r"Failed to download", "Maven distribution or dependency download failed (network)"),
    (r"UnknownHostException", "Maven repository host resolution failed (network unavailable)"),
    (r"Could not resolve dependencies", "Maven dependencies unresolvable (offline cache/network)"),
    (r"Could not find or load main class", "Maven wrapper distribution missing or broken"),
    (
        r"Could not find a valid Docker environment",
        "requires Docker (testcontainers), not available",
    ),
    (r"DockerClientException", "requires Docker (testcontainers), Docker API unavailable"),
)


@dataclass(frozen=True)
class CapsuleUnit:
    """One capsule to replay: the zip payload plus its auxiliaries."""

    name: str
    zip_path: Path | None
    dir_path: Path | None
    store_records: tuple[ObjectMetadata, ...]
    sha256: str
    base_ref: str
    head_ref: str


@dataclass(frozen=True)
class EvidenceReport:
    """Result of verifying a capsule's recorded evidence."""

    problems: tuple[str, ...]

    @property
    def inconsistent(self) -> bool:
        return bool(self.problems)


@dataclass(frozen=True)
class RunResult:
    """Result of executing a capsule run script."""

    exit_code: int
    stdout: str
    stderr: str
    timed_out: bool
    error: str


@dataclass(frozen=True)
class ReplayOutcome:
    """The classified outcome of one replay attempt."""

    outcome: str
    reason: str
    verdict: str | None
    base_exit: int | None
    head_exit: int | None


def canonical_manifest_digest(manifest: dict[str, Any]) -> str:
    """Recompute manifest_digest with create_capsule's canonical rule.

    The digest is sha256 over the canonical serialization of the manifest
    WITHOUT the digest field (sorted keys, no whitespace) — the same rule
    agent/nodes/create_capsule.py uses, so any stored copy can be verified.
    """
    without_digest = {k: v for k, v in manifest.items() if k != "manifest_digest"}
    canonical = json.dumps(without_digest, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode()).hexdigest()


def read_zip_json(zip_path: Path, member: str) -> dict[str, Any] | None:
    """Read one JSON member of a capsule zip, or None when absent."""
    try:
        with zipfile.ZipFile(zip_path, "r") as archive:
            if member not in archive.namelist():
                return None
            loaded = json.loads(archive.read(member))
            return loaded if isinstance(loaded, dict) else None
    except (zipfile.BadZipFile, json.JSONDecodeError, OSError):
        return None


def read_zip_text(zip_path: Path, member: str) -> str:
    """Read one text member of a capsule zip; '' when absent or broken."""
    try:
        with zipfile.ZipFile(zip_path, "r") as archive:
            if member not in archive.namelist():
                return ""
            return archive.read(member).decode("utf-8", "replace").strip()
    except (zipfile.BadZipFile, OSError):
        return ""


def read_zip_members(zip_path: Path) -> list[str] | None:
    """The member name list of a zip, or None when the zip is corrupt."""
    try:
        with zipfile.ZipFile(zip_path, "r") as archive:
            return list(archive.namelist())
    except (zipfile.BadZipFile, OSError):
        return None


def collect_store_inventory(
    store: ObjectMetadataStore, capsules_dir: Path,
) -> dict[str, Any]:
    """Summarize the capsule records of the object-metadata store.

    Records are grouped by where their path_hint points: under this repo's
    capsules/ (this_repo), an existing path elsewhere (other_repo), or a
    path that no longer exists (orphan). Joined records are those whose
    payload digest matches a capsule zip under capsules_dir.
    """
    digest_to_records: dict[str, list[ObjectMetadata]] = {}
    total = 0
    this_repo = 0
    other_repo = 0
    orphan = 0
    for record in store.by_kind("capsule"):
        total += 1
        hint = Path(record.path_hint) if record.path_hint else None
        digest = normalize_payload_digest(record.digests.get("payload_sha256", ""))
        digest_to_records.setdefault(digest, []).append(record)
        if hint is None or not hint.exists():
            orphan += 1
        elif capsules_dir.resolve() in hint.resolve().parents:
            this_repo += 1
        else:
            other_repo += 1
    joined = 0
    for zip_path in sorted(capsules_dir.glob("capsule-*.zip")):
        digest = normalize_payload_digest(payload_sha256_of_file(zip_path))
        joined += len(digest_to_records.get(digest, []))
    return {
        "capsule_records_total": total,
        "this_repo_paths": this_repo,
        "other_repo_paths": other_repo,
        "orphan_paths": orphan,
        "joined_to_zip_digests": joined,
    }


def enumerate_capsules(
    capsules_dir: Path, store: ObjectMetadataStore | None,
) -> tuple[list[CapsuleUnit], dict[str, Any]]:
    """Enumerate replay units: zips, extracted dirs and store records.

    A unit is keyed by capsule name (the zip stem). Store records join a
    unit when their payload digest equals the zip's payload digest, which
    is content identity rather than path inference. Extracted capsule
    directories without a matching zip become zip-less units that the
    replay path cannot consume.
    """
    store = store if store is not None else default_object_metadata_store()
    try:
        inventory = collect_store_inventory(store, capsules_dir)
        digest_records: dict[str, list[ObjectMetadata]] = {}
        for record in store.by_kind("capsule"):
            digest = normalize_payload_digest(record.digests.get("payload_sha256", ""))
            if _SHA256_HEX_RE.fullmatch(digest):
                digest_records.setdefault(digest, []).append(record)

        units: list[CapsuleUnit] = []
        zip_paths = sorted(capsules_dir.glob("capsule-*.zip"))
        for zip_path in zip_paths:
            name = zip_path.stem
            sha256 = payload_sha256_of_file(zip_path)
            records = digest_records.get(sha256, [])
            seen: set[str] = set()
            unique_records: list[ObjectMetadata] = []
            for record in records:
                if record.object_id not in seen:
                    seen.add(record.object_id)
                    unique_records.append(record)
            dir_path = capsules_dir / name
            units.append(
                CapsuleUnit(
                    name=name,
                    zip_path=zip_path,
                    dir_path=dir_path if dir_path.is_dir() else None,
                    store_records=tuple(unique_records),
                    sha256=sha256,
                    base_ref=read_zip_text(zip_path, "fixtures/base-ref.txt"),
                    head_ref=read_zip_text(zip_path, "fixtures/head-ref.txt"),
                )
            )
        for dir_path in sorted(capsules_dir.glob("capsule-*")):
            if not dir_path.is_dir():
                continue
            if any(unit.name == dir_path.name for unit in units):
                continue
            units.append(
                CapsuleUnit(
                    name=dir_path.name,
                    zip_path=None,
                    dir_path=dir_path,
                    store_records=(),
                    sha256="",
                    base_ref="",
                    head_ref="",
                )
            )
        return units, inventory
    finally:
        if store is not None:
            store.close()


def verify_evidence(unit: CapsuleUnit) -> EvidenceReport:
    """Verify the capsule's recorded evidence without executing anything.

    Checks: zip payload present and readable; manifest.json present (the
    existing replay path rejects capsules without one); manifest_digest
    recomputes to the recorded value; manifest/finding evidence_digest
    agreement; extracted directory copy agreement; metadata-store payload
    digest agreement.
    """
    problems: list[str] = []
    zip_path = unit.zip_path
    if zip_path is None:
        problems.append(
            "no capsule .zip payload — the replay path cannot consume an extracted layout"
        )
        return EvidenceReport(tuple(problems))
    if read_zip_members(zip_path) is None:
        problems.append("corrupt zip payload (cannot be opened)")
        return EvidenceReport(tuple(problems))
    manifest = read_zip_json(zip_path, "manifest.json")
    if manifest is None:
        problems.append(
            "manifest.json missing — the existing replay path rejects the capsule "
            "as corrupt; recorded evidence cannot be established"
        )
        return EvidenceReport(tuple(problems))
    recorded = str(manifest.get("manifest_digest") or "")
    recomputed = canonical_manifest_digest(manifest)
    if normalize_payload_digest(recorded) != recomputed:
        problems.append(
            f"manifest_digest mismatch: recorded {recorded[:12]!r}..., recomputed "
            f"{recomputed[:12]}... — the manifest was modified after recording"
        )
    finding = read_zip_json(zip_path, "finding.json")
    manifest_evidence = str(manifest.get("evidence_digest") or "")
    finding_evidence = str((finding or {}).get("evidence_digest") or "")
    if (
        manifest_evidence
        and finding_evidence
        and normalize_payload_digest(manifest_evidence)
        != normalize_payload_digest(finding_evidence)
    ):
        problems.append(
            f"evidence_digest disagreement: manifest {manifest_evidence[:12]!r}... "
            f"vs finding {finding_evidence[:12]!r}..."
        )
    if unit.dir_path is not None:
        dir_manifest_path = unit.dir_path / "manifest.json"
        try:
            dir_manifest = json.loads(dir_manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            dir_manifest = None
        if dir_manifest is None:
            problems.append(
                "extracted capsule directory exists but its manifest.json is unreadable"
            )
        elif dir_manifest != manifest:
            problems.append("extracted capsule directory manifest differs from the zip manifest")
    for record in unit.store_records:
        recorded_digest = normalize_payload_digest(record.digests.get("payload_sha256", ""))
        if recorded_digest != unit.sha256:
            problems.append(
                f"object-metadata store record {record.object_id[:8]} records payload "
                f"{recorded_digest[:12]}... but the zip payload hashes to {unit.sha256[:12]}... "
                "— the capsule was modified after it was recorded"
            )
    return EvidenceReport(tuple(problems))


def recorded_claim(manifest: dict[str, Any]) -> dict[str, Any]:
    """The recorded blocker_check conditions, tolerating missing fields."""
    blocker_check = manifest.get("blocker_check") or {}
    conditions = blocker_check.get("blocker_conditions") or {}
    return {
        "2_base_head_execution": bool(conditions.get("2_base_head_execution")),
        "4_db_behavior_evidence": bool(conditions.get("4_db_behavior_evidence")),
        "5_capsule_replayable": bool(conditions.get("5_capsule_replayable")),
    }


def expected_verdict_for(manifest: dict[str, Any]) -> str:
    """The verdict the capsule's recorded evidence commits to."""
    claim = recorded_claim(manifest)
    if claim["2_base_head_execution"]:
        return VERDICT_CONFIRMED
    return NO_RUNTIME_CLAIM


def parse_verdict(output: str) -> str | None:
    """Parse the run script's verdict marker, or None."""
    match = _VERDICT_RE.search(output)
    if match is None:
        return None
    return match.group(1)


def parse_exit_codes(output: str) -> tuple[int | None, int | None]:
    """Parse the Base/Head maven test exit codes printed by the run script."""
    base_exit: int | None = None
    head_exit: int | None = None
    for match in _EXIT_CODE_RE.finditer(output):
        value = int(match.group(2))
        if match.group(1) == "Base":
            base_exit = value
        else:
            head_exit = value
    return base_exit, head_exit


def env_failure_reason(output: str) -> str:
    """The environment failure this output proves, or ''."""
    for pattern, reason in _ENV_FAILURE_PATTERNS:
        if re.search(pattern, output):
            return reason
    return ""


def classify_replay(expected: str, run: RunResult) -> ReplayOutcome:
    """Classify one executed replay against the capsule's recorded claim."""
    output = run.stdout + "\n" + run.stderr
    base_exit, head_exit = parse_exit_codes(output)
    verdict = parse_verdict(output)
    env_reason = env_failure_reason(output)
    if run.error:
        reason = f"run script could not be executed: {run.error}"
        return ReplayOutcome(OUTCOME_ENV, reason, None, None, None)
    if run.timed_out:
        reason = f"run script timed out (limit {DEFAULT_TIMEOUT_S:.0f}s)"
        return ReplayOutcome(OUTCOME_FAILED, reason, verdict, base_exit, head_exit)
    if env_reason and verdict != VERDICT_CONFIRMED:
        suffix = f" — run script verdict {verdict}" if verdict else ""
        return ReplayOutcome(OUTCOME_ENV, env_reason + suffix, verdict, base_exit, head_exit)
    if verdict is None:
        if run.exit_code != 0:
            tail = output.strip().splitlines()[-3:]
            reason = (
                f"run script exited {run.exit_code} without a verdict — "
                f"output tail: {' | '.join(tail)}"
            )
        else:
            reason = "run script produced no verdict"
        return ReplayOutcome(OUTCOME_FAILED, reason, None, base_exit, head_exit)
    if verdict == VERDICT_CONFIRMED:
        if expected == VERDICT_CONFIRMED:
            reason = (
                "recorded base_pass_head_fail reproduced — run script verdict "
                "REGRESSION CONFIRMED"
            )
        else:
            reason = (
                "static-only recorded evidence; runtime replay additionally confirmed the "
                "regression (verdict REGRESSION CONFIRMED) — same conclusion, stronger evidence"
            )
        return ReplayOutcome(OUTCOME_SAME, reason, verdict, base_exit, head_exit)
    if expected == VERDICT_CONFIRMED:
        reason = (
            f"recorded base_pass_head_fail NOT reproduced — run script verdict {verdict} "
            f"(base_exit={base_exit}, head_exit={head_exit})"
        )
    else:
        reason = (
            f"static-only recorded evidence; runtime verdict {verdict} does not reproduce "
            "the finding"
        )
    return ReplayOutcome(OUTCOME_FAILED, reason, verdict, base_exit, head_exit)


def probe_environment() -> dict[str, Any]:
    """Probe the tools a real replay needs (never fabricates availability)."""
    def which(name: str) -> str | None:
        found = shutil.which(name)
        return found if found else None

    java_version = ""
    java = which("java")
    if java:
        try:
            java_version = subprocess.run(
                [java, "-version"], capture_output=True, text=True, timeout=30,
                check=False,
            ).stderr.strip().splitlines()[0]
        except (OSError, subprocess.TimeoutExpired, IndexError):
            java_version = ""
    maven_dist = Path.home() / ".m2" / "wrapper" / "dists"
    return {
        "python": sys.executable,
        "git": which("git"),
        "pwsh": which("pwsh"),
        "bash": which("bash"),
        "java": java,
        "java_version": java_version,
        "maven_dist_cache": str(maven_dist) if maven_dist.is_dir() else "",
    }


def prepare_temp_worktree(
    repo_root: Path, refs: frozenset[str], work_root: Path,
) -> dict[str, Any]:
    """Prepare a throwaway git repo whose root is the demo project.

    The capsule run scripts expect a git repository whose ROOT is the Maven
    project (mvnw at the repo root), while in this repo the demo project
    lives at demo/spring-backend. We clone the repo into a temp directory
    (read-only with respect to the real repo) and rebuild each needed ref
    with git subtree split --prefix=demo/spring-backend, retagging it with
    its original name, so the temp repo's root IS the demo project and the
    capsule run scripts' git checkout <ref> + ./mvnw work unchanged. If
    subtree split is unavailable, the fallback rebuilds the same refs from
    git archive content (byte-identical project trees, synthetic commits).
    """
    clone = work_root / "src"
    result = subprocess.run(
        ["git", "clone", "--quiet", "--no-checkout", "--", str(repo_root), str(clone)],
        capture_output=True, text=True, timeout=600, check=False,
    )
    if result.returncode != 0:
        return {
            "repo": None,
            "mechanism": "none",
            "refs": {},
            "error": result.stderr.strip()[:400],
        }
    try:
        return _prepare_via_subtree(clone, refs)
    except (OSError, subprocess.SubprocessError, tarfile.TarError):
        return _prepare_via_archive(clone, refs)


def _prepare_via_subtree(clone: Path, refs: frozenset[str]) -> dict[str, Any]:
    """Rebuild refs via git subtree split (real per-commit history)."""
    resolved: dict[str, bool] = {}
    for ref in sorted(refs):
        split = subprocess.run(
            [
                "git", "-C", str(clone), "subtree", "split",
                "--prefix=demo/spring-backend", ref,
            ],
            capture_output=True, text=True, timeout=900, check=False,
        )
        if split.returncode != 0:
            raise subprocess.SubprocessError(
                f"subtree split failed for {ref}: {split.stderr.strip()[:200]}"
            )
        commit = split.stdout.strip().splitlines()[-1].strip()
        tagged = subprocess.run(
            ["git", "-C", str(clone), "tag", "-f", ref, commit],
            capture_output=True, text=True, timeout=120, check=False,
        )
        if tagged.returncode != 0:
            raise subprocess.SubprocessError(
                f"tagging {ref} failed: {tagged.stderr.strip()[:200]}"
            )
        resolved[ref] = True
    first = sorted(refs)[0]
    subprocess.run(
        ["git", "-C", str(clone), "checkout", "--quiet", "-f", first],
        capture_output=True, text=True, timeout=600, check=False,
    )
    return {"repo": clone, "mechanism": "subtree-split", "refs": resolved, "error": ""}


def _prepare_via_archive(clone: Path, refs: frozenset[str]) -> dict[str, Any]:
    """Fallback: rebuild refs from git archive content, synthetic commits."""
    synthetic = clone.parent / "synthetic"
    synthetic.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["git", "-C", str(synthetic), "init", "--quiet", "-b", "main"],
        capture_output=True, text=True, timeout=120, check=False,
    )
    resolved: dict[str, bool] = {}
    for ref in sorted(refs):
        archive = subprocess.run(
            ["git", "-C", str(clone), "archive", "--format=tar", ref, "demo/spring-backend"],
            capture_output=True, timeout=900, check=False,
        )
        if archive.returncode != 0:
            resolved[ref] = False
            continue
        for entry in synthetic.iterdir():
            if entry.name != ".git":
                if entry.is_dir():
                    shutil.rmtree(entry, ignore_errors=True)
                else:
                    entry.unlink(missing_ok=True)
        prefix = "demo/spring-backend/"
        with tarfile.open(fileobj=io.BytesIO(archive.stdout), mode="r:") as tar:
            for member in tar.getmembers():
                if not member.name.startswith(prefix):
                    continue
                relative = member.name[len(prefix):]
                if not relative or member.isdir():
                    continue
                target = synthetic / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                extracted = tar.extractfile(member)
                if extracted is not None:
                    target.write_bytes(extracted.read())
        subprocess.run(
            ["git", "-C", str(synthetic), "add", "-A"],
            capture_output=True, text=True, timeout=300, check=False,
        )
        committed = subprocess.run(
            [
                "git", "-C", str(synthetic), "-c", "user.name=bench-replay",
                "-c", "user.email=bench-replay@specproof.invalid",
                "commit", "--quiet", "-m", f"archive of {ref}",
            ],
            capture_output=True, text=True, timeout=300, check=False,
        )
        if committed.returncode != 0:
            resolved[ref] = False
            continue
        subprocess.run(
            ["git", "-C", str(synthetic), "tag", "-f", ref, "HEAD"],
            capture_output=True, text=True, timeout=120, check=False,
        )
        resolved[ref] = True
    subprocess.run(
        ["git", "-C", str(synthetic), "checkout", "--quiet", "-f", sorted(refs)[0]],
        capture_output=True, text=True, timeout=600, check=False,
    )
    return {
        "repo": synthetic,
        "mechanism": "archive-synthetic",
        "refs": resolved,
        "error": "",
    }


def extract_via_replay_cli(
    python: str, repo_root: Path, zip_path: Path, out_dir: Path,
) -> tuple[bool, str]:
    """Run the existing replay CLI to extract the capsule and write its report."""
    out_dir.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        [
            python, "-m", "cli.specproof.main", "replay",
            str(zip_path), "--output-dir", str(out_dir),
        ],
        cwd=repo_root,
        capture_output=True,
        text=True,
        timeout=CLI_TIMEOUT_S,
        check=False,
    )
    return result.returncode == 0, (result.stdout + "\n" + result.stderr).strip()


def execute_run_script(extracted_dir: Path, repo: Path, timeout: float) -> RunResult:
    """Execute the capsule's own replay script against the temp worktree.

    Windows-native first: run.ps1 via pwsh; otherwise run.sh via bash.
    The scripts are executed unmodified, exactly as generated.
    """
    script_ps1 = extracted_dir / "run.ps1"
    script_sh = extracted_dir / "run.sh"
    pwsh = shutil.which("pwsh")
    bash = shutil.which("bash")
    if script_ps1.exists() and pwsh:
        command = [
            pwsh, "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass",
            "-File", str(script_ps1), "-RepoDir", str(repo),
        ]
    elif script_sh.exists() and bash:
        command = [bash, str(script_sh), str(repo)]
    elif script_ps1.exists() or script_sh.exists():
        return RunResult(
            exit_code=-1, stdout="", stderr="", timed_out=False,
            error="no pwsh/bash executor available for the capsule run script",
        )
    else:
        return RunResult(
            exit_code=-1, stdout="", stderr="", timed_out=False,
            error="capsule carries no run.sh / run.ps1 replay script",
        )
    try:
        result = subprocess.run(
            command, cwd=extracted_dir, capture_output=True, text=True,
            timeout=timeout, check=False,
        )
        return RunResult(
            exit_code=result.returncode,
            stdout=result.stdout,
            stderr=result.stderr,
            timed_out=False,
            error="",
        )
    except subprocess.TimeoutExpired:
        return RunResult(exit_code=-1, stdout="", stderr="", timed_out=True, error="")
    except OSError as exc:
        return RunResult(
            exit_code=-1, stdout="", stderr="", timed_out=False, error=str(exc)
        )


def check_generated_test_presence(repo: Path) -> dict[str, bool]:
    """Whether the capsule's generated test landed where Maven compiles.

    The generated run scripts copy generated-tests/* into <repo>/src/test/;
    Maven compiles only src/test/java/**. Both facts are recorded honestly.
    """
    def contains_specproof_generated(directory: Path) -> bool:
        if not directory.is_dir():
            return False
        return any(path.is_file() for path in directory.rglob("SpecProofGeneratedTest*.java"))

    return {
        "in_test_java": contains_specproof_generated(repo / "src" / "test" / "java"),
        "in_test_root": contains_specproof_generated(repo / "src" / "test"),
    }


def build_unit_entry(
    unit: CapsuleUnit, manifest: dict[str, Any] | None,
) -> dict[str, Any]:
    """The static (pre-replay) facts of one unit for the results JSON."""
    entry: dict[str, Any] = {
        "unit": unit.name,
        "sources": {
            "zip": unit.zip_path is not None,
            "dir": unit.dir_path is not None,
            "store_records": len(unit.store_records),
        },
        "zip_path": str(unit.zip_path) if unit.zip_path else "",
        "dir_path": str(unit.dir_path) if unit.dir_path else "",
        "payload_sha256": unit.sha256,
        "base_ref": unit.base_ref,
        "head_ref": unit.head_ref,
        "finding_id": (manifest or {}).get("finding_id", ""),
        "severity": (manifest or {}).get("severity", ""),
        "evidence_type": (manifest or {}).get("evidence_type", ""),
        "db_state_verdict": (manifest or {}).get("db_state_verdict", ""),
        "recorded": recorded_claim(manifest or {}),
    }
    return entry


def run_bench(args: argparse.Namespace) -> dict[str, Any]:
    """Run the batch replay and return the results document."""
    capsules_dir = Path(args.capsules_dir)
    repo_root = Path(args.repo)
    environment = probe_environment()

    units, inventory = enumerate_capsules(capsules_dir, None)
    if args.limit is not None:
        units = units[: max(0, args.limit)]

    # Evidence gate first: only consistent capsules proceed to execution.
    evidence_by_unit: dict[str, EvidenceReport] = {}
    manifest_by_unit: dict[str, dict[str, Any] | None] = {}
    for unit in units:
        manifest = read_zip_json(unit.zip_path, "manifest.json") if unit.zip_path else None
        manifest_by_unit[unit.name] = manifest
        evidence_by_unit[unit.name] = verify_evidence(unit)

    runnable = [
        unit for unit in units
        if not evidence_by_unit[unit.name].inconsistent and unit.zip_path is not None
    ]
    refs = frozenset(
        ref for unit in runnable
        for ref in (unit.base_ref, unit.head_ref) if ref
    )

    work_root = Path(tempfile.mkdtemp(prefix="specproof-bench-replay-"))
    worktree: dict[str, Any] = {
        "repo": None, "mechanism": "none", "refs": {}, "error": "",
    }
    prep_error = ""
    executor_missing = ""
    if runnable:
        if not environment["pwsh"] and not environment["bash"]:
            executor_missing = "no capsule run-script executor (pwsh/bash) available"
        elif not environment["git"]:
            executor_missing = "git is not available — a temp replay worktree cannot be prepared"
        else:
            worktree = prepare_temp_worktree(repo_root, refs, work_root)
            if worktree["repo"] is None:
                prep_error = worktree.get("error") or "temp worktree preparation failed"

    entries: list[dict[str, Any]] = []
    repo_dir: Path | None = worktree["repo"]
    for index, unit in enumerate(units, start=1):
        entry = build_unit_entry(unit, manifest_by_unit[unit.name])
        evidence = evidence_by_unit[unit.name]
        entry["evidence_problems"] = list(evidence.problems)
        duration_s = 0.0
        if evidence.inconsistent:
            outcome = ReplayOutcome(
                OUTCOME_EVIDENCE, "; ".join(evidence.problems), None, None, None,
            )
        elif executor_missing:
            outcome = ReplayOutcome(OUTCOME_ENV, executor_missing, None, None, None)
        elif prep_error:
            outcome = ReplayOutcome(
                OUTCOME_ENV, f"temp worktree preparation failed: {prep_error}",
                None, None, None,
            )
        else:
            assert repo_dir is not None
            worktree_refs: dict[str, bool] = worktree["refs"]
            missing_refs = [
                ref for ref in (unit.base_ref, unit.head_ref)
                if ref and not worktree_refs.get(ref, False)
            ]
            if missing_refs:
                outcome = ReplayOutcome(
                    OUTCOME_ENV,
                    f"recorded ref(s) {', '.join(missing_refs)} not available in the repo",
                    None, None, None,
                )
            else:
                extracted = work_root / "extracted" / unit.name
                ok, cli_output = extract_via_replay_cli(
                    sys.executable, repo_root, unit.zip_path or Path(), extracted,
                )
                entry["replay_cli"] = {
                    "ok": ok,
                    "report": str(extracted / "replay-report.json"),
                    "output_tail": cli_output.strip().splitlines()[-5:],
                }
                if not ok:
                    cli_tail = " | ".join(cli_output.strip().splitlines()[-8:])
                    if "digest mismatch" in cli_output or "Corrupt capsule" in cli_output:
                        outcome = ReplayOutcome(
                            OUTCOME_EVIDENCE,
                            f"existing replay path rejected the capsule: {cli_tail}",
                            None, None, None,
                        )
                    else:
                        outcome = ReplayOutcome(
                            OUTCOME_FAILED,
                            f"existing replay path failed: {cli_tail}",
                            None, None, None,
                        )
                else:
                    manifest = json.loads(
                        (extracted / "manifest.json").read_text(encoding="utf-8")
                    )
                    expected = expected_verdict_for(manifest)
                    entry["expected_verdict"] = expected
                    unit_start = time.monotonic()
                    run = execute_run_script(extracted, repo_dir, args.timeout)
                    duration_s = time.monotonic() - unit_start
                    outcome = classify_replay(expected, run)
                    entry["run_exit_code"] = run.exit_code
                    entry["timed_out"] = run.timed_out
                    entry["run_output_tail"] = (
                        (run.stdout + "\n" + run.stderr).strip().splitlines()[-8:]
                    )
                    generated_test = check_generated_test_presence(repo_dir)
                    entry["generated_test"] = generated_test
                    if (
                        outcome.outcome == OUTCOME_FAILED
                        and generated_test["in_test_root"]
                        and not generated_test["in_test_java"]
                    ):
                        outcome = ReplayOutcome(
                            outcome.outcome,
                            outcome.reason + " — root cause: the capsule's generated test "
                            "was injected into src/test/ (outside Maven's test source root "
                            "src/test/java/) and was never compiled",
                            outcome.verdict,
                            outcome.base_exit,
                            outcome.head_exit,
                        )
        entry["outcome"] = outcome.outcome
        entry["reason"] = outcome.reason
        entry["verdict"] = outcome.verdict
        entry["base_exit"] = outcome.base_exit
        entry["head_exit"] = outcome.head_exit
        entry["duration_s"] = round(duration_s, 2)
        entries.append(entry)
        print(
            f"[{index}/{len(units)}] {unit.name} -> {outcome.outcome}"
            f"{' (' + outcome.verdict + ')' if outcome.verdict else ''}",
            flush=True,
        )

    totals = dict.fromkeys(OUTCOMES, 0)
    for entry in entries:
        totals[entry["outcome"]] += 1
    enumerated = len(entries)
    rate = totals[OUTCOME_SAME] / enumerated if enumerated else 0.0
    executed = enumerated - totals[OUTCOME_ENV]
    rate_excluding_env = totals[OUTCOME_SAME] / executed if executed else 0.0
    kept = args.keep_worktree
    if not kept:
        shutil.rmtree(work_root, ignore_errors=True)
    results: dict[str, Any] = {
        "generated_at": datetime.now(UTC).isoformat(),
        "tool": "scripts/bench_replay.py",
        "repo_root": str(repo_root.resolve()),
        "capsules_dir": str(capsules_dir.resolve()),
        "limit": args.limit,
        "worktree": {
            "mechanism": worktree["mechanism"],
            "path": str(worktree["repo"]) if kept and worktree["repo"] else "",
            "prep_error": prep_error,
        },
        "environment": environment,
        "store": inventory,
        "totals": {
            "enumerated": enumerated,
            **totals,
            "success_rate": round(rate, 4),
            "success_rate_excluding_env_mismatch": round(rate_excluding_env, 4),
            "gate_replay_success_rate_095": rate >= GATE_REPLAY_SUCCESS_RATE,
        },
        "capsules": entries,
    }
    write_reports(results, Path(args.output_json), Path(args.output_md))
    return results


def render_markdown(results: dict[str, Any]) -> str:
    """Render the human-readable results document."""
    totals = results["totals"]
    env = results["environment"]
    store = results["store"]
    worktree = results["worktree"]
    lines: list[str] = [
        "# Capsule Replay Batch Results (主计划 §5.9 / 阶段2)",
        "",
        f"- Generated at: {results['generated_at']}",
        f"- Tool: `{results['tool']}`",
        f"- Repo: `{results['repo_root']}`",
        f"- Capsules dir: `{results['capsules_dir']}`",
        f"- Temp worktree: `{worktree['mechanism']}`" + (
            f" (`{worktree['path']}`)" if worktree["path"] else ""
        ),
        f"- Limit: {results['limit'] if results['limit'] is not None else 'none (full run)'}",
        "",
        "## Replay success rate",
        "",
        "| metric | value |",
        "|---|---|",
        f"| capsules enumerated | {totals['enumerated']} |",
        f"| same_conclusion | {totals['same_conclusion']} |",
        f"| env_mismatch | {totals['env_mismatch']} |",
        f"| evidence_inconsistent | {totals['evidence_inconsistent']} |",
        f"| replay_failed | {totals['replay_failed']} |",
        "| **success rate (same_conclusion / enumerated)** | "
        f"**{totals['success_rate']:.4f}** |",
        "| success rate excluding env_mismatch | "
        f"{totals['success_rate_excluding_env_mismatch']:.4f} |",
        "| Go/No-Go gate #4 (replay 成功率 ≥ 95%) | "
        f"{'PASS' if totals['gate_replay_success_rate_095'] else 'FAIL'} |",
        "",
        "## Environment",
        "",
        "| tool | status |",
        "|---|---|",
        f"| python | `{env['python']}` |",
        f"| git | `{env['git'] or 'MISSING'}` |",
        f"| pwsh | `{env['pwsh'] or 'MISSING'}` |",
        f"| bash | `{env['bash'] or 'MISSING'}` |",
        f"| java | `{env['java'] or 'MISSING'}` ({env['java_version'] or 'no version line'}) |",
        f"| Maven distribution cache | `{env['maven_dist_cache'] or 'MISSING'}` |",
        "",
        "## Object-metadata store",
        "",
        "| metric | value |",
        "|---|---|",
        f"| capsule records total | {store['capsule_records_total']} |",
        f"| records under this repo's capsules/ | {store['this_repo_paths']} |",
        f"| records pointing at other repos | {store['other_repo_paths']} |",
        f"| records whose payload no longer exists | {store['orphan_paths']} |",
        f"| records joined to a zip by payload digest | {store['joined_to_zip_digests']} |",
        "",
        "## Per-capsule results",
        "",
        "| capsule | severity | evidence | base | head | verdict | outcome | reason |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for entry in results["capsules"]:
        reason = entry["reason"].replace("|", "\\|")
        lines.append(
            f"| {entry['unit']} | {entry['severity']} | {entry['evidence_type']} "
            f"| {entry['base_ref']} | {entry['head_ref']} | {entry['verdict'] or '-'} "
            f"| {entry['outcome']} | {reason} |"
        )
    reason_counts: dict[str, int] = {}
    for entry in results["capsules"]:
        reason_counts[entry["reason"]] = reason_counts.get(entry["reason"], 0) + 1
    lines += [
        "",
        "## Observed root causes (deduplicated reasons)",
        "",
    ]
    for reason, count in sorted(reason_counts.items(), key=lambda item: (-item[1], item[0])):
        lines.append(f"- ×{count} — {reason}")
    lines += [
        "",
        "## Method notes",
        "",
        "- Classification is anchored on each capsule's own recorded evidence: "
        "blocker_check condition 2_base_head_execution=true commits the capsule to a "
        "differential base-pass/head-fail regression, so only a REGRESSION CONFIRMED "
        "verdict is same_conclusion; static-only capsules carry no runtime claim and a "
        "runtime confirmation is recorded as the same conclusion (strengthened).",
        "- Capsules are replayed through the existing path "
        "(python -m cli.specproof.main replay), then their own generated run script is "
        "executed unmodified against a temp worktree — observed replay defects are reported "
        "in the reasons, never patched around.",
        f"- Temp worktree mechanism `{worktree['mechanism']}`: the repo is cloned to a temp "
        "dir (the real repo is never mutated) and each needed ref is rebuilt with the demo "
        "project at the repo root, because the generated run scripts expect mvnw at the "
        "git root while this repo keeps the project under demo/spring-backend.",
        "- The existing replay CLI appends one replay_report record per capsule to the "
        "object-metadata store — documented CLI behavior, outside the repo.",
        "- env_mismatch is only reported for environment failures, always with the exact "
        "reason; verdicts are never fabricated.",
    ]
    return "\n".join(lines) + "\n"


def write_reports(results: dict[str, Any], json_path: Path, md_path: Path) -> None:
    """Write the machine-readable and human-readable results documents."""
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(results, indent=2), encoding="utf-8")
    md_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.write_text(render_markdown(results), encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="bench_replay",
        description="Batch-replay every capsule and measure the real replay success rate.",
    )
    parser.add_argument(
        "--limit", type=int, default=None,
        help="smoke mode: replay only the first N enumerated capsules",
    )
    parser.add_argument(
        "--capsules-dir", default=str(REPO_ROOT / "capsules"),
        help="directory containing capsule-*.zip payloads",
    )
    parser.add_argument(
        "--repo", default=str(REPO_ROOT),
        help="git repository the temp replay worktree is cloned from",
    )
    parser.add_argument(
        "--output-json", default=str(REPO_ROOT / "docs" / "eval" / "replay-results.json"),
        help="machine-readable results path",
    )
    parser.add_argument(
        "--output-md", default=str(REPO_ROOT / "docs" / "eval" / "replay-results.md"),
        help="human-readable results path",
    )
    parser.add_argument(
        "--timeout", type=float, default=DEFAULT_TIMEOUT_S,
        help="per-capsule run script timeout in seconds",
    )
    parser.add_argument(
        "--keep-worktree", action="store_true",
        help="keep the temp worktree and extracted capsules after the run",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    results = run_bench(args)
    totals = results["totals"]
    print(
        f"\nreplay success rate: {totals['same_conclusion']}/{totals['enumerated']} "
        f"= {totals['success_rate']:.4f} (gate >= 0.95: "
        f"{'PASS' if totals['gate_replay_success_rate_095'] else 'FAIL'})",
        flush=True,
    )
    print(f"results: {results['tool']} -> docs/eval/replay-results.json + .md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
