"""Seed honest demo content for the SpecProof local one-command experience (W43).

Seeded content (all idempotent, every row/artifact marked 【演示】):

* 3 terminal VERIFY jobs (AUTH 越权回归 → BLOCKED, 邮箱变更事件追踪 →
  VERIFIED, Broker 重试幂等回归 → VERIFIED). The /jobs API has no endpoint
  that creates terminal history or persists a matrix, so these rows are
  written into the SAME MySQL store the API reads (storage.mysql) with the
  same column discipline, plus contracts/findings rows, the persisted
  pipeline summary, Redis stage events, a real-format certificate /
  rejection notice built with evidence.certificate (the exact builders the
  CLI verify flow uses), and small demo capsule zips.
* 1 agent-console job 【演示】修复 double 函数. It is created through the
  REAL POST /agent/jobs endpoint when the API is reachable (its title and
  events live in the console process exactly like a user-created job), and
  its plan is attached through the SAME durable agent store the API reads
  (storage.agent_jobs) — no API endpoint exists to set a plan, so the store
  is the only honest path. It is seeded in AWAITING_APPROVAL so the tour can
  approve the plan and the final gate through the real API.

Store selection matches the API exactly:
* verification jobs: MySQL only — storage.mysql has no fallback and the API
  answers 503 without MySQL, so seeding degrades to a warning instead of
  pretending;
* agent jobs: SPECPROOF_AGENT_JOBS_URL ("" in-memory / "sqlite:<path>" /
  "mysql://..."), same fail-closed rules as api/routes/agent_console.py.

Idempotency: verify jobs use stable uuid5 keys; the agent job is matched by
its spec digest in the durable store. Re-running never duplicates.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import uuid
import zipfile
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, TypedDict, cast

_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from evidence.certificate import (  # noqa: E402
    build_rejection_notice,
    issue_certificate,
)
from storage.agent_jobs import (  # noqa: E402
    TERMINAL_JOB_STATUSES,
    AgentJob,
    AgentJobStore,
    InMemoryAgentJobStore,
    InvalidJobTransitionError,
    MySqlAgentJobStore,
    SqliteAgentJobStore,
    compute_spec_digest,
)
from storage.mysql import MySQLStore  # noqa: E402
from storage.redis import RedisStore  # noqa: E402

# ── Demo content constants ────────────────────────────────────────────────

DEMO_MARK = "【演示】"
SEED_NAMESPACE = "specproof-demo"
DEMO_REPO_PATH = "demo/spring-backend"
DEMO_SPEC_PATH = "demo/requirement.txt"

SEED_AGENT_TASK_NAME = f"{DEMO_MARK}修复 double 函数"
SEED_AGENT_SPEC_TEXT = (
    "任务: 修复工具类 MathUtil.double 函数的符号错误。\n"
    "现状: double(int n) 对负数输入返回了错误的符号结果 (例如 double(-3) "
    "返回正数), 正数与零行为正常。\n"
    "要求:\n"
    "1. 修复负数分支的符号判断逻辑;\n"
    "2. 补充负数与零的边界单元测试;\n"
    "3. 全量回归测试必须通过 (mvnw test 全绿)。\n"
    "门禁: 提交前必须运行回归测试并保持全部测试绿色; 禁止改动无关文件。"
)
SEED_AGENT_PLAN: dict[str, Any] = {
    "version": 1,
    "steps": [
        {
            "index": 0,
            "title": "定位 double 实现与现有测试",
            "summary": "read_file + grep 定位 MathUtil.double 及其单测",
            "status": "pending",
        },
        {
            "index": 1,
            "title": "修复负数符号判断",
            "summary": "edit: 修正负数分支的符号逻辑",
            "status": "pending",
        },
        {
            "index": 2,
            "title": "补充负数/零边界测试",
            "summary": "edit: 新增负数与零的边界用例",
            "status": "pending",
        },
        {
            "index": 3,
            "title": "回归验证",
            "summary": "运行 mvnw test, 全绿后产出结果",
            "status": "pending",
        },
    ],
}

_REPLAY_MD = (
    "# 【演示】Bug Capsule\n\n"
    "本胶囊由 scripts/seed_demo.py 为本地体验生成, 用于演示 Findings 页的\n"
    "胶囊下载链路, 未经过真实差分执行。真实的胶囊由验证管道在捕获反例时\n"
    "生成, 包含 Base/Head 复现步骤与取证输出。\n"
)
_REPRODUCE_PS1 = (
    "# 【演示】复现脚本占位 — 真实胶囊中的脚本可重建反例环境\n"
    "Write-Host 'demo capsule: generated by scripts/seed_demo.py'\n"
)


class DemoContract(TypedDict):
    contract_id_str: str
    requirement_text: str
    checker_type: str
    expected_behavior: str
    result: str
    evidence_ref: str


class DemoFinding(TypedDict):
    contract_id: str
    severity: str
    confidence: float
    evidence_type: str
    impact_path: list[str]
    description: str


class DemoStage(TypedDict):
    node: str
    message: str


class DemoVerifyTemplate(TypedDict):
    key: str
    title: str
    base_ref: str
    head_ref: str
    status: str
    verdict: str
    contracts: list[DemoContract]
    findings: list[DemoFinding]
    stages: list[DemoStage]


def stable_demo_uuid(key: str) -> str:
    """Deterministic seed id — the idempotency anchor for re-runs."""
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"{SEED_NAMESPACE}:{key}"))


def demo_verify_templates() -> list[DemoVerifyTemplate]:
    """The 3 demo verify jobs (pure data; no store, no network, no secrets)."""
    return [
        {
            "key": "verify-auth-regression",
            "title": f"{DEMO_MARK}AUTH 越权回归",
            "base_ref": "base",
            "head_ref": "head-v1",
            "status": "BLOCKED",
            "verdict": "BLOCKED",
            "contracts": [
                {
                    "contract_id_str": "AUTH-01",
                    "requirement_text": "只有通过认证的用户才能变更邮箱地址",
                    "checker_type": "annotation",
                    "expected_behavior": "匿名调用 changeEmailWithoutAuth 应返回 401",
                    "result": "FAIL",
                    "evidence_ref": "runtime-junit + static-diff",
                },
                {
                    "contract_id_str": "AUTH-02",
                    "requirement_text": "变更邮箱必须携带当前密码重新认证",
                    "checker_type": "annotation",
                    "expected_behavior": "缺少当前密码时返回 403",
                    "result": "PASS",
                    "evidence_ref": "runtime-junit",
                },
            ],
            "findings": [
                {
                    "contract_id": "AUTH-01",
                    "severity": "BLOCKER",
                    "confidence": 0.97,
                    "evidence_type": "runtime_diff",
                    "impact_path": ["src/main/java/com/demo/UserController.java"],
                    "description": (
                        "head-v1 移除了 changeEmailWithoutAuth 上的 @PreAuthorize: "
                        "匿名请求返回 200 (基线上为 401), H2 取证显示邮箱被改写成 "
                        "attacker@evil.com — 静态 diff 与 JUnit 差分双重确认"
                    ),
                }
            ],
            "stages": [
                {"node": "intake", "message": "任务受理, 校验 base/head 引用"},
                {"node": "compile_contracts", "message": "从需求编译 2 条契约"},
                {"node": "run_differential", "message": "Base/Head 差分执行 (JUnit)"},
                {"node": "review_court", "message": "AUTH-01 确认 BLOCKER"},
                {"node": "build_matrix", "message": "生成需求-证据矩阵"},
                {"node": "create_capsule", "message": "生成 AUTH-01 Bug Capsule"},
                {"node": "publish_report", "message": "产出拒绝通知, 判定 BLOCKED"},
            ],
        },
        {
            "key": "verify-rel-email-event",
            "title": f"{DEMO_MARK}邮箱变更事件追踪",
            "base_ref": "base",
            "head_ref": "p0.5-verified-v1",
            "status": "VERIFIED",
            "verdict": "VERIFIED",
            "contracts": [
                {
                    "contract_id_str": "REL-01",
                    "requirement_text": "邮箱变更成功后必须发布领域事件",
                    "checker_type": "probe",
                    "expected_behavior": "成功变更后发布 EmailChanged 事件",
                    "result": "PASS",
                    "evidence_ref": "runtime-junit",
                },
                {
                    "contract_id_str": "REL-02",
                    "requirement_text": "事件必须携带时间戳与变更前邮箱",
                    "checker_type": "probe",
                    "expected_behavior": "事件负载含 timestamp 与 old_email",
                    "result": "PASS",
                    "evidence_ref": "runtime-junit",
                },
            ],
            "findings": [],
            "stages": [
                {"node": "intake", "message": "任务受理, 校验 base/head 引用"},
                {"node": "compile_contracts", "message": "从需求编译 2 条契约"},
                {"node": "run_differential", "message": "Base/Head 差分执行 (JUnit)"},
                {"node": "build_matrix", "message": "生成需求-证据矩阵"},
                {"node": "publish_report", "message": "全部契约通过, 判定 VERIFIED"},
            ],
        },
        {
            "key": "verify-rel-broker-retry",
            "title": f"{DEMO_MARK}Broker 重试幂等回归",
            "base_ref": "base",
            "head_ref": "head-v1",
            "status": "VERIFIED",
            "verdict": "VERIFIED",
            "contracts": [
                {
                    "contract_id_str": "REL-03",
                    "requirement_text": "Broker 投递失败重试后不得产生重复事件",
                    "checker_type": "probe",
                    "expected_behavior": "重试后恰有一条事件被消费",
                    "result": "PASS",
                    "evidence_ref": "runtime-junit",
                },
                {
                    "contract_id_str": "REL-04",
                    "requirement_text": "邮箱未变化时不得发布事件",
                    "checker_type": "probe",
                    "expected_behavior": "no-op 更新不发布任何事件",
                    "result": "PASS",
                    "evidence_ref": "runtime-junit",
                },
            ],
            "findings": [],
            "stages": [
                {"node": "intake", "message": "任务受理, 校验 base/head 引用"},
                {"node": "compile_contracts", "message": "从需求编译 2 条契约"},
                {"node": "run_differential", "message": "Base/Head 差分执行 (JUnit)"},
                {"node": "build_matrix", "message": "生成需求-证据矩阵"},
                {"node": "publish_report", "message": "全部契约通过, 判定 VERIFIED"},
            ],
        },
    ]


def _capsule_name(job_id: str, contract_id: str) -> str:
    return f"capsule-{job_id[:8]}-{contract_id}.zip"


def _requirements_text() -> str:
    spec = _PROJECT_ROOT / DEMO_SPEC_PATH
    if spec.is_file():
        try:
            return spec.read_text(encoding="utf-8")
        except OSError:
            pass
    return "演示需求: 认证、事件与幂等契约 (seeded demo spec)"


def _head_sha(template: DemoVerifyTemplate) -> str:
    repo = _PROJECT_ROOT / DEMO_REPO_PATH
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", template["head_ref"]],
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
        if proc.returncode == 0:
            return proc.stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return ""
    return ""


def _contracts_for_certificate(
    template: DemoVerifyTemplate,
) -> list[dict[str, Any]]:
    return [
        {
            "id": c["contract_id_str"],
            "result": c["result"],
            "checker_type": c["checker_type"],
            "expected_behavior": c["expected_behavior"],
            "evidence_ref": c["evidence_ref"],
        }
        for c in template["contracts"]
    ]


def _evidence_digests(contracts: list[dict[str, Any]]) -> list[str]:
    return [
        "sha256:"
        + hashlib.sha256(
            f"{c.get('id', '')}:{c.get('evidence_ref', '')}".encode()
        ).hexdigest()
        for c in contracts
    ]


def _summary_for(template: DemoVerifyTemplate, job_id: str) -> dict[str, Any]:
    findings = [
        {
            "id": str(stable_demo_uuid(f"verify:{template['key']}:finding:{i}")),
            "severity": f["severity"],
            "contract_id": f["contract_id"],
            "confidence": f["confidence"],
            "evidence_type": f["evidence_type"],
            "type": "runtime_diff",
            "location": f["impact_path"][0] if f["impact_path"] else "",
            "description": f["description"],
        }
        for i, f in enumerate(template["findings"])
    ]
    contracts_total = len(template["contracts"])
    passed = sum(1 for c in template["contracts"] if c["result"] == "PASS")
    failed = sum(1 for c in template["contracts"] if c["result"] == "FAIL")
    return {
        "verdict": template["verdict"],
        "contracts_total": contracts_total,
        "matrix_passed": passed,
        "matrix_failed": failed,
        "matrix_unverified": contracts_total - passed - failed,
        "findings": findings,
        "capsules": [
            _capsule_name(job_id, f["contract_id"]) for f in template["findings"]
        ],
        "report_path": "",
        "retrieval_note": "seeded demo data (【演示】)",
        "errors": [],
    }


def _insert_verify_job(
    store: MySQLStore, template: DemoVerifyTemplate, job_id: str,
) -> None:
    store.insert_job(
        {
            "id": job_id,
            "repo_path": DEMO_REPO_PATH,
            "base_ref": template["base_ref"],
            "head_ref": template["head_ref"],
            "spec_path": DEMO_SPEC_PATH,
            "status": template["status"],
            "depth": "FAST",
            "github_check": None,
        }
    )
    for i, contract in enumerate(template["contracts"]):
        store.insert_contract(
            {
                "id": str(stable_demo_uuid(f"verify:{template['key']}:contract:{i}")),
                "job_id": job_id,
                **contract,
            }
        )
    for i, finding in enumerate(template["findings"]):
        finding_id = str(stable_demo_uuid(f"verify:{template['key']}:finding:{i}"))
        store.insert_finding(
            {
                "id": finding_id,
                "job_id": job_id,
                "contract_id": finding["contract_id"],
                "severity": finding["severity"],
                "confidence": finding["confidence"],
                "evidence_type": finding["evidence_type"],
                "impact_path": json.dumps(finding["impact_path"]),
                "capsule_path": _capsule_name(job_id, finding["contract_id"]),
            }
        )
    store.save_job_summary(job_id, _summary_for(template, job_id))


def _write_documents(
    template: DemoVerifyTemplate, job_id: str, reports_dir: Path,
) -> None:
    """Write certificate / rejection notice (real builders; skip if present)."""
    short = job_id[:8]
    if template["verdict"] == "VERIFIED":
        path = reports_dir / f"merge-certificate-{short}.json"
        if path.is_file():
            return
        certificate = issue_certificate(
            repository=DEMO_REPO_PATH,
            commit_sha=_head_sha(template),
            requirements_text=_requirements_text(),
            contracts=_contracts_for_certificate(template),
            evidence_digests=_evidence_digests(_contracts_for_certificate(template)),
        )
        if certificate is None:  # honest: never fabricate a certificate
            return
        reports_dir.mkdir(parents=True, exist_ok=True)
        path.write_text(certificate.to_json(), encoding="utf-8")
        return
    path = reports_dir / f"rejection-notice-{short}.json"
    if path.is_file():
        return
    notice = build_rejection_notice(
        repository=DEMO_REPO_PATH,
        commit_sha=_head_sha(template),
        requirements_text=_requirements_text(),
        contracts=_contracts_for_certificate(template),
        reasons=[f["description"] for f in template["findings"]] or [
            "contracts unverified"
        ],
    )
    reports_dir.mkdir(parents=True, exist_ok=True)
    path.write_text(notice.to_json(), encoding="utf-8")


def _write_capsules(
    template: DemoVerifyTemplate, job_id: str, capsules_dir: Path,
) -> None:
    for finding in template["findings"]:
        name = _capsule_name(job_id, finding["contract_id"])
        path = capsules_dir / name
        if path.is_file():
            continue
        payload = json.dumps(
            {
                "demo": True,
                "job_id": job_id,
                "contract_id": finding["contract_id"],
                "severity": finding["severity"],
                "note": (
                    "演示胶囊 — 由 scripts/seed_demo.py 生成, 未经过真实差分执行"
                ),
                "created_at": datetime.now(UTC).isoformat(),
            },
            ensure_ascii=False,
            indent=2,
        )
        capsules_dir.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("capsule.json", payload)
            zf.writestr("REPLAY.md", _REPLAY_MD)
            zf.writestr("reproduce.ps1", _REPRODUCE_PS1)


def _write_stages(
    template: DemoVerifyTemplate, job_id: str, redis: RedisStore | None,
) -> bool:
    if redis is None:
        return False
    try:
        if not redis.is_ready() or redis.stream_length(job_id) > 0:
            return False
        total = len(template["stages"])
        for i, stage in enumerate(template["stages"]):
            redis.xadd_progress(
                job_id,
                stage["node"],
                "completed",
                message=stage["message"],
                percent=round((i + 1) / total * 100.0, 1),
            )
        return True
    except Exception as exc:  # noqa: BLE001 — stages are optional telemetry
        print(f"[seed] 阶段流写入失败 (Redis): {exc}", file=sys.stderr)
        return False


def _split_sql_statements(sql: str) -> list[str]:
    """Split a migration file on ';' — comment-safe.

    storage/migrations.py splits first and strips comment lines afterwards,
    which turns a ';' inside a full-line comment (0005's rollback note,
    0006's "INSERT-only;" bullet) into a broken SQL fragment on a fresh
    database. Stripping comment lines BEFORE splitting keeps those files
    valid; the seed only ever runs statements from the repo's own
    migrations directory.
    """
    without_comments = "\n".join(
        line for line in sql.splitlines() if not line.strip().startswith("--")
    )
    statements: list[str] = []
    for raw in without_comments.split(";"):
        stmt = raw.strip()
        if stmt:
            statements.append(stmt)
    return statements


def ensure_mysql_schema(store: MySQLStore) -> list[str]:
    """Apply pending versioned migrations; returns the applied file names.

    Uses the exact same migration files and schema_migrations bookkeeping
    as storage.migrations.MigrationRunner (one transaction per migration,
    versions recorded once), with the comment-safe splitter above. The API
    does not migrate at startup, so the seed is the one place in the
    one-command flow that can guarantee a readable schema. Already-applied
    versions are skipped, so re-runs are no-ops and the stock runner later
    agrees with us.
    """
    migrations_dir = _PROJECT_ROOT / "infra" / "mysql" / "migrations"
    with store.connection() as conn:
        conn.cursor().execute(
            "CREATE TABLE IF NOT EXISTS schema_migrations ("
            "version INT PRIMARY KEY, "
            "name VARCHAR(255) NOT NULL, "
            "applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
            ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
        )
    with store.connection() as conn:
        cur = conn.cursor()
        cur.execute("SELECT version FROM schema_migrations")
        applied = {int(row["version"]) for row in cur.fetchall()}
    if not migrations_dir.exists():
        return []
    names: list[str] = []
    for path in sorted(migrations_dir.glob("*.sql")):
        head, _, rest = path.name.partition("_")
        try:
            version = int(head)
        except ValueError as exc:
            raise ValueError(
                f"migration filename must start with a number: {path.name}"
            ) from exc
        if version in applied:
            continue
        statements = _split_sql_statements(path.read_text(encoding="utf-8"))
        with store.connection() as conn:
            for stmt in statements:
                conn.cursor().execute(stmt)
            conn.cursor().execute(
                "INSERT INTO schema_migrations (version, name) VALUES (%s, %s)",
                (version, rest),
            )
        names.append(path.name)
    return names


def seed_verify_jobs(
    store: MySQLStore,
    *,
    reports_dir: Path,
    capsules_dir: Path,
    redis: RedisStore | None = None,
) -> tuple[int, int]:
    """Insert demo verify history + artifacts. Returns (created, skipped).

    Applies pending schema migrations first (idempotent, versioned) so the
    API and the dashboard have tables to read. Every write is guarded:
    existing job rows are skipped and artifact files are only created when
    missing, so re-runs never duplicate.
    """
    ensure_mysql_schema(store)
    created = 0
    skipped = 0
    for template in demo_verify_templates():
        job_id = stable_demo_uuid(f"verify:{template['key']}")
        if store.get_job(job_id) is None:
            _insert_verify_job(store, template, job_id)
            created += 1
        else:
            skipped += 1
        _write_documents(template, job_id, reports_dir)
        _write_capsules(template, job_id, capsules_dir)
        _write_stages(template, job_id, redis)
    return created, skipped


# ── Agent demo job ─────────────────────────────────────────────────────────


def build_agent_store(url: str) -> AgentJobStore:
    """Mirror api/routes/agent_console.py backend selection (fail closed)."""
    target = url.strip()
    if not target:
        return InMemoryAgentJobStore()
    if target.startswith("sqlite:"):
        store: AgentJobStore = SqliteAgentJobStore(target[len("sqlite:"):])
    elif target.startswith(("mysql://", "mysql+pymysql://")):
        store = MySqlAgentJobStore(target)
    else:
        raise ValueError(
            "SPECPROOF_AGENT_JOBS_URL must be '', 'sqlite:<path>' or a "
            f"mysql:// URL (got {url!r}) — refusing to pick an unknown "
            "agent job store backend"
        )
    store.ensure_schema()
    return store


def find_agent_job_by_spec_digest(
    store: AgentJobStore, spec_text: str,
) -> AgentJob | None:
    """The durable idempotency key for the agent seed: sha256(spec_text)."""
    digest = compute_spec_digest(spec_text)
    for job in store.list(limit=500):
        if job.spec_digest == digest:
            return job
    return None


def demo_agent_plan() -> dict[str, Any]:
    """Deep copy of the demo plan with a fresh created_at timestamp."""
    plan = cast(dict[str, Any], json.loads(json.dumps(SEED_AGENT_PLAN)))
    plan["created_at"] = datetime.now(UTC).isoformat()
    return plan


def attach_agent_plan(
    store: AgentJobStore, job_id: str, plan: dict[str, Any],
) -> bool:
    """Attach the demo plan unless one exists or the job is terminal."""
    job = store.get(job_id)
    if job is None or job.plan_json is not None:
        return False
    if job.status in TERMINAL_JOB_STATUSES:
        return False
    try:
        store.set_plan(job_id, plan)
    except InvalidJobTransitionError:
        return False
    return True


def seed_agent_job_in_store(
    store: AgentJobStore,
    *,
    job_id: str | None = None,
    spec_text: str = SEED_AGENT_SPEC_TEXT,
    plan: dict[str, Any] | None = None,
) -> tuple[AgentJob, bool]:
    """Create (or reuse) the demo agent job in a durable store.

    Returns (job, created). The default id is a stable uuid5; the spec
    digest is the fallback key so a job created earlier through the API
    (random id) is still recognized. The demo plan is attached unless a
    plan already exists or the job is terminal (a repeat seed must not
    overwrite a user's approvals).
    """
    target_id = job_id or stable_demo_uuid("agent:double-fix")
    existing = store.get(target_id)
    if existing is None:
        existing = find_agent_job_by_spec_digest(store, spec_text)
    if existing is None:
        job = store.create(target_id, spec_text)
        created = True
    else:
        job = existing
        created = False
    attach_agent_plan(store, job.id, plan if plan is not None else demo_agent_plan())
    fresh = store.get(job.id)  # create() returns a pre-write snapshot; re-read
    return (fresh if fresh is not None else job), created


def seed_agent_job_via_api(
    api_base: str, api_key: str, store: AgentJobStore,
) -> tuple[str, bool, str]:
    """Create the demo agent job through the real POST /agent/jobs.

    Returns (job_id, created, note). The console title and the "job created"
    event live in the API process, so the exercised path is the only one
    that renders the 【演示】 title. The plan is attached through the same
    durable store the API reads (no API endpoint sets a plan). When the API
    is unreachable the seeding degrades to the store path.
    """
    import httpx

    existing = find_agent_job_by_spec_digest(store, SEED_AGENT_SPEC_TEXT)
    if existing is not None:
        attached = attach_agent_plan(store, existing.id, demo_agent_plan())
        note = "already exists (plan attached)" if attached else "already exists"
        return existing.id, False, note
    headers = {"X-API-Key": api_key}
    try:
        resp = httpx.post(
            f"{api_base.rstrip('/')}/agent/jobs",
            json={
                "repo_path": DEMO_REPO_PATH,
                "spec_text": SEED_AGENT_SPEC_TEXT,
                "task_name": SEED_AGENT_TASK_NAME,
            },
            headers=headers,
            timeout=30.0,
        )
        resp.raise_for_status()
        job_id = str(resp.json()["job_id"])
        attach_agent_plan(store, job_id, demo_agent_plan())
        return job_id, True, "created via POST /agent/jobs"
    except (httpx.HTTPError, KeyError, ValueError) as exc:
        job, created = seed_agent_job_in_store(store)
        return job.id, created, f"API unreachable ({exc}) — store fallback"


# ── CLI ────────────────────────────────────────────────────────────────────


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python scripts/seed_demo.py",
        description="Seed idempotent demo content for the SpecProof local experience.",
    )
    parser.add_argument(
        "--api-base",
        default="http://127.0.0.1:8000",
        help="Base URL of the running API (agent job goes through POST /agent/jobs)",
    )
    parser.add_argument(
        "--api-key",
        default="",
        help="X-API-Key for the API (defaults to SPECPROOF_API_KEY)",
    )
    parser.add_argument(
        "--agent-store-url",
        default="",
        help="Agent job store URL (defaults to SPECPROOF_AGENT_JOBS_URL)",
    )
    return parser


def _print_summary(stats: dict[str, Any], warnings: list[str], note: str) -> None:
    print(
        "[seed] 验证任务(演示历史): "
        f"新建 {stats['verify_created']}, 已存在 {stats['verify_skipped']} "
        "(存储: MySQL — 与 API 相同)"
    )
    print(
        f"[seed] Agent 任务: {stats['agent_job_id']} {SEED_AGENT_TASK_NAME} "
        f"— {note} — 状态: AWAITING_APPROVAL"
    )
    for warning in warnings:
        print(f"[seed] 警告: {warning}")


def main(argv: list[str] | None = None) -> int:
    import os

    args = build_parser().parse_args(argv)
    api_base: str = args.api_base
    api_key: str = args.api_key or os.getenv("SPECPROOF_API_KEY", "").strip()
    agent_url: str = args.agent_store_url or os.getenv(
        "SPECPROOF_AGENT_JOBS_URL", ""
    ).strip()

    warnings: list[str] = []
    stats: dict[str, Any] = {
        "verify_created": 0,
        "verify_skipped": 0,
        "agent_job_id": "",
        "agent_created": False,
    }

    # 1) Verify history — MySQL only, the same store the API reads.
    try:
        mysql = MySQLStore()
        if mysql.is_ready():
            stats["verify_created"], stats["verify_skipped"] = seed_verify_jobs(
                mysql,
                reports_dir=_PROJECT_ROOT / "reports",
                capsules_dir=_PROJECT_ROOT / "capsules",
                redis=RedisStore(),
            )
        else:
            warnings.append("MySQL 未就绪 — 跳过验证任务演示数据 (仅 Agent 任务)")
    except Exception as exc:  # noqa: BLE001 — degrade honestly, never break start
        warnings.append(f"验证任务播种失败: {exc}")

    # 2) Agent demo job — POST when the API is up, durable store always.
    try:
        store = build_agent_store(agent_url)
        if api_key and api_base:
            job_id, created, note = seed_agent_job_via_api(api_base, api_key, store)
        else:
            job, created = seed_agent_job_in_store(store)
            job_id = job.id
            note = "store-only seeding (未配置 API key/base)"
        stats["agent_job_id"] = job_id
        stats["agent_created"] = created
    except Exception as exc:  # noqa: BLE001
        print(f"[seed] Agent 任务播种失败: {exc}", file=sys.stderr)
        warnings.append(f"Agent 任务播种失败: {exc}")
        note = "failed"

    _print_summary(stats, warnings, note)
    return 0


if __name__ == "__main__":
    sys.exit(main())
