"""Unit tests for the capsule replay scripts generated by create_capsule."""


def _finding() -> dict[str, object]:
    """A minimal confirmed finding for replay-script generation."""
    return {
        "severity": "MAJOR",
        "contract_id": "AUTH-01",
        "description": "differential regression",
        "evidence_type": "base_pass_head_fail",
    }


def test_replay_scripts_copy_generated_tests_into_maven_test_root() -> None:
    """Pin the generated-test copy target to Maven's src/test/java/.

    Maven only compiles tests that live under the test source root
    src/test/java/. The historical scripts copied generated tests into the
    bare src/test/ directory, so the injected differential test never
    compiled and the replay could not reproduce the finding (28.57% replay
    success in docs/eval/replay-results.md). This test pins the corrected
    copy target and the directory-creation fallback for both run.sh and
    run.ps1, so the regression cannot return.
    """
    from agent.nodes.create_capsule import _build_replay_script

    finding = _finding()
    sh = _build_replay_script("F-1", finding, "capsule-F-1", is_windows=False)
    ps1 = _build_replay_script("F-1", finding, "capsule-F-1", is_windows=True)

    # bash: create src/test/java when missing, then copy into it
    assert 'TEST_DEST="$REPO_DIR/src/test/java"' in sh
    assert 'mkdir -p "$TEST_DEST"' in sh
    assert 'cp -r "$TEST_SRC"/* "$TEST_DEST/"' in sh
    assert 'cp -r "$TEST_SRC"/* "$REPO_DIR/src/test/"' not in sh

    # PowerShell: create src\test\java when missing, then copy into it
    assert '$destDir = "$RepoDir\\src\\test\\java"' in ps1
    assert 'New-Item -ItemType Directory -Force -Path $destDir' in ps1
    assert 'Copy-Item -Recurse -Force "$TestSrc\\*" "$destDir\\"' in ps1
    assert '= "$RepoDir\\src\\test"' not in ps1
